version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=doctorapi
      - DB_USER=root
      - DB_PASSWORD=lkdkldsk787832jkd
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - POSTGRES_DB=doctorapi
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=lkdkldsk787832jkd
