# Generated by Django 4.0.5 on 2022-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="birthday",
            field=models.DateField(),
        ),
    ]
