# Generated by Django 4.0.5 on 2022-06-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_item_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="item_url",
        ),
    ]
