# Generated by Django 4.0.5 on 2022-06-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_alter_doctor_item_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="item_url",
        ),
    ]
